name       : fuse-exfat
version    : 1.2.0
release    : 2
source     :
    - https://github.com/relan/exfat/archive/v1.2.0.tar.gz : e806a5275dfef8597c2c4bbe73699672f0fbb354034005ab41cf88e446a00196
license    : GPL-3.0
summary    : Free exFAT file system implementation
description: |
    Free exFAT file system implementation
rundeps    :
    - fuse
builddeps  :
    - pkgconfig(fuse)
    - util-linux-devel
    - exfat-utils
setup      : |
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    %make_install
    mkdir -p %installroot%/sbin
    mv %installroot%/usr/sbin/* %installroot%/sbin/
    rm -rf %installroot%/usr
