name       : fuse-exfat
version    : 1.2.8
release    : 4
source     :
    - https://github.com/relan/exfat/archive/v1.2.8.tar.gz : 778474bfbcd92e35bba5b88bd7ad3f6400328256636abb9031bfcc1ce15ed887
license    : GPL-3.0
component  : system.utils
summary    : Free exFAT file system implementation
description: |
    Free exFAT file system implementation
builddeps  :
    - pkgconfig(fuse)
    - util-linux-devel
    - exfat-utils
rundeps    :
    - fuse
setup      : |
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    %make_install
    mkdir -p %installroot%/sbin
    mv %installroot%/usr/sbin/* %installroot%/sbin/
    rm -rf %installroot%/usr
